# Generated by Django 4.2.4 on 2023-08-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0002_rename_author_paper_authors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="id",
            field=models.CharField(
                editable=False, max_length=255, primary_key=True, serialize=False
            ),
        ),
    ]
